import {Bar,Line} from 'react-chartjs-2';import {Chart as ChartJS,CategoryScale,LinearScale,BarElement,PointElement,LineElement,Tooltip,Legend,Filler} from 'chart.js';import type {Series} from './types';import type {ReactNode} from 'react';
ChartJS.register(CategoryScale,LinearScale,BarElement,PointElement,LineElement,Tooltip,Legend,Filler);
export const money=(n=0,c:'KRW'|'JPY'='KRW')=>new Intl.NumberFormat(c==='KRW'?'ko-KR':'ja-JP',{style:'currency',currency:c,maximumFractionDigits:0}).format(n);
export function KPI({label,value,note}:{label:string;value:string;note?:string}){return <article className="kpi"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</article>}
export function ChartCard({title,series,kind='bar',wide=false,stacked=false,actions}:{title:string;series?:Series;kind?:'bar'|'line';wide?:boolean;stacked?:boolean;actions?:ReactNode}){const empty=!series?.labels?.length;const dual=series?.datasets?.some(d=>d.yAxisID==='y1');const chartOpts=stacked?stackedOpts:dual?dualOpts:opts;return <section className={`card chart-card ${wide?'wide':''}`}><div className="chart-card-head"><h3>{title}</h3>{actions}</div><div className="chart">{empty?<div className="empty">No data returned</div>:kind==='line'?<Line data={series!} options={chartOpts}/>:<Bar data={series!} options={chartOpts}/>}</div></section>}
const opts={responsive:true,maintainAspectRatio:false,interaction:{mode:'index' as const,intersect:false},plugins:{legend:{position:'bottom' as const,labels:{usePointStyle:true,boxWidth:8}}},scales:{x:{grid:{display:false}},y:{beginAtZero:true,grid:{color:'#edf0f4'}}}};
const dualOpts={...opts,scales:{...opts.scales,y1:{beginAtZero:true,position:'right' as const,grid:{drawOnChartArea:false}}}};
const stackedOpts={...opts,scales:{x:{...opts.scales.x,stacked:true},y:{...opts.scales.y,stacked:true}}};
export function DataTable({title,rows,scroll=false,actions}:{title:string;rows?:Record<string,string|number>[];scroll?:boolean;actions?:ReactNode}){const keys=rows?.length?Object.keys(rows[0]):[];return <section className={`card wide ${scroll?'daily-table':''}`}><div className="chart-card-head"><h3>{title}</h3>{actions}</div>{!rows?.length?<div className="empty">No data returned</div>:<div className="table-wrap"><table><thead><tr>{keys.map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{keys.map(k=><td key={k}>{r[k]}</td>)}</tr>)}</tbody></table></div>}</section>}
